# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eureka_main_page_point', models.PositiveIntegerField(verbose_name='Ilo\u015b\u0107 punkt\xf3w potrzebnych eurece na dostanie si\u0119 na g\u0142\xf3wna stron\u0119.')),
            ],
        ),
    ]
