# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('actual_state', models.CharField(blank=True, choices=[('Przetwarzanie', 'Przetwarzanie'), ('Naprawiono', 'Naprawiono'), ('B\u0142\u0119dne zg\u0142oszenie', 'B\u0142\u0119dne zg\u0142oszenie')], default='Przetwarzanie', max_length=30, verbose_name='Aktualny status')),
                ('comment_admin', models.TextField(blank=True, max_length=1000, verbose_name='Komentarz administratora')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email kontaktowy (niewymagany)')),
                ('error_login_state', models.CharField(choices=[('Zalogowany', 'Zalogowany'), ('Niezalogowany', 'Niezalogowany'), ('W obu przypadkach', 'W obu przypadkach'), ('Nie dotyczy', 'Nie dotyczy')], max_length=30, verbose_name='B\u0142\u0105d wyst\u0119puje tylko wtedy kiedy jestem')),
                ('error_code', models.CharField(choices=[('400', '400'), ('403', '403'), ('404', '404'), ('500', '500'), ('Ca\u0142kowicie pusta strona', 'Ca\u0142kowicie pusta strona'), ('Sam interfejs (menu, stopka)', 'Sam interfejs (menu, stopka)'), ('Ci\u0105gle \u0142aduj\u0105ca si\u0119 strona', 'Ci\u0105gle \u0142aduj\u0105ca si\u0119 strona'), ('Nie dotyczy', 'Nie dotyczy')], max_length=30, verbose_name='W czasie wyst\u0105pienia b\u0142\u0119du pojawia si\u0119')),
                ('error_type', models.CharField(choices=[('Nieszkodliwy', 'Nieszkodliwy'), ('Niebezpieczny', 'Niebezpieczny'), ('Krytyczny', 'Krytyczny')], max_length=30, verbose_name='Typ b\u0142\u0119du')),
                ('error_link', models.URLField(verbose_name='B\u0142\u0105d wyst\u0119puje na stronie (ca\u0142y link wraz z https://www.)')),
                ('error_description', models.TextField(max_length=1000, verbose_name='Opis b\u0142\u0119du')),
                ('error_image', models.ImageField(blank=True, null=True, upload_to='error_images', verbose_name='Zdj\u0119cie (niewymagane)')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
