# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('diary', '0001_initial'),
        ('linked', '0001_initial'),
        ('mask', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eureka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=80, verbose_name='Tytu\u0142')),
                ('description', models.TextField(max_length=300, verbose_name='Opis')),
                ('link', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()], verbose_name='Link do instrukcji, filmu lub \u017ar\xf3d\u0142a np.: http://www.')),
                ('content_type', models.CharField(choices=[('0', 'Autorska'), ('1', 'Cudza')], default='0', max_length=9, verbose_name='Typ tre\u015bci')),
                ('preview_image', models.ImageField(upload_to='preview_images', verbose_name='Miniaturka')),
                ('is_waiting', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Opublikowano')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('comments', models.ManyToManyField(to='comments.Comment', verbose_name='Komentarze')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Stworzone przez')),
                ('diarys', models.ManyToManyField(to='diary.Diary')),
            ],
            options={
                'permissions': (('is_owner', 'Is owner eureka'), ('can_vote', 'Can votes eureka'), ('can_view', 'Can view eureka')),
            },
        ),
        migrations.CreateModel(
            name='EurekaInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='EurekaInstructionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=40, verbose_name='Tytu\u0142 kroku')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Tre\u015b\u0107 kroku')),
                ('step_slug', models.SlugField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='eurekainstruction',
            name='steps',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='eureka.EurekaInstructionStep'),
        ),
        migrations.AddField(
            model_name='eureka',
            name='eurekaInstruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eureka.EurekaInstruction'),
        ),
        migrations.AddField(
            model_name='eureka',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='eureka_eureka_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eureka',
            name='links',
            field=models.ManyToManyField(to='linked.Linked', verbose_name='Powi\u0105zane'),
        ),
        migrations.AddField(
            model_name='eureka',
            name='mask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.DeleteMask'),
        ),
        migrations.AddField(
            model_name='eureka',
            name='moderations',
            field=models.ManyToManyField(to='moderation.Moderation'),
        ),
    ]
