# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0002_auto_20170417_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eureka',
            name='sympathizers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Sympathizer', verbose_name=b'Sympatycy'),
        ),
    ]
