# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0007_auto_20170419_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='eureka',
            name='difficult',
            field=models.CharField(blank=True, choices=[('easy', '\u0141atwy'), ('medium', '\u015aredni'), ('hard', 'Trudny')], max_length=20, verbose_name='Poziom trudno\u015bci'),
        ),
    ]
