# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0008_eureka_difficult'),
    ]

    operations = [
        migrations.AddField(
            model_name='eureka',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cena orientacyjna'),
        ),
    ]
