# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sympathizer',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'Nazwa'),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
