# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(default='default_images/avatar/favicon.png', upload_to='avatar_images', verbose_name='Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Imi\u0119')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Nazwisko')),
                ('public_email', models.EmailField(blank=True, max_length=30, verbose_name='Publiczny email')),
                ('website', models.URLField(blank=True, verbose_name='Strona www')),
                ('town', models.CharField(blank=True, max_length=20, verbose_name='Miasto')),
                ('social_facebook', models.URLField(blank=True, max_length=100, verbose_name='Facebook')),
                ('social_twitter', models.URLField(blank=True, max_length=100, verbose_name='Twitter')),
                ('social_google_plus', models.URLField(blank=True, max_length=100, verbose_name='Google plus')),
                ('social_linkedin', models.URLField(blank=True, max_length=100, verbose_name='Linkedin')),
                ('social_youtube', models.URLField(blank=True, max_length=100, verbose_name='YouTube')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Opis konta')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_account.SettingsAvatar'),
        ),
        migrations.AddField(
            model_name='settings',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_account.SettingsProfile'),
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
