# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concept', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='sympathizers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Sympathizer', verbose_name=b'Sympatycy'),
        ),
        migrations.AddField(
            model_name='concept',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.DefaultTagged', to='tags.DefaultTag', verbose_name=b'Tagi'),
        ),
    ]
