# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0003_auto_20170417_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='sympathizers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Sympathizer', verbose_name=b'Sympatycy'),
        ),
    ]
