# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0011_auto_20170423_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
