# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_conversation_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='seeed',
            field=models.BooleanField(default=True),
        ),
    ]
