# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0013_conversation_seeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='seeed',
        ),
        migrations.AddField(
            model_name='conversation',
            name='seeed',
            field=models.ManyToManyField(blank=True, related_name='seeed', to=settings.AUTH_USER_MODEL),
        ),
    ]
